### ISSUE TITLE
Setting version to 1.1.0 results in a quick test failure

### ISSUE THREAD

**Issue by BMurri** [ga4gh/openapi-test-runner#67]
log from following the docker instructions:

```
[37mProvided server: http://tes:***@tesinttest-53111224-5682-00728.southcentralus.cloudapp.azure.com/ version: 1.1.0[0m
[37mProvided tags - include: [] exclude: [][0m
[37mProvided test path: ('tests',)[0m
[33m
[0m
[33m###########################     Initiating Test-1 for tests/create_task_ignore_error.yml     ###########################[0m
[37mYAML file valid for Test: tests/create_task_ignore_error.yml[0m
[37mRunning tests for sub-job-1 -> create_task[0m
[37mRequest Body Schema validation successful for POST /tasks[0m
[37mSending POST request to http://tes:***@tesinttest-53111224-5682-00728.southcentralus.cloudapp.azure.com/v1/tasks. Query Parameters - {}[0m
[37mPOST /tasks response status code matched[0m
[37mResponse Schema validation successful for POST /tasks[0m
[37mRunning tests for sub-job-2 -> get_task[0m
[37mSending GET request to http://tes:***@tesinttest-53111224-5682-00728.southcentralus.cloudapp.azure.com/v1/tasks/3d4b1aa5b05e42b38cb45dea5d3bfac9. Query Parameters - {'view': 'FULL'}[0m
[37mGET /tasks/{id} response status code matched[0m
[37mResponse Schema validation successful for GET /tasks/{id}[0m
Traceback (most recent call last):
  File "/usr/local/bin/openapi-test-runner", line 33, in <module>
    sys.exit(load_entry_point('openapi-test-runner==0.1.0', 'console_scripts', 'openapi-test-runner')())
  File "/usr/local/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click-8.1.3-py3.8.egg/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/openapi_test_runner-0.1.0-py3.8.egg/compliance_suite/cli.py", line 100, in report
  File "/usr/local/lib/python3.8/site-packages/openapi_test_runner-0.1.0-py3.8.egg/compliance_suite/job_runner.py", line 237, in run_jobs
  File "/usr/local/lib/python3.8/site-packages/openapi_test_runner-0.1.0-py3.8.egg/compliance_suite/job_runner.py", line 201, in initialize_test
  File "/usr/local/lib/python3.8/site-packages/openapi_test_runner-0.1.0-py3.8.egg/compliance_suite/test_runner.py", line 380, in run_tests
  File "/usr/local/lib/python3.8/site-packages/openapi_test_runner-0.1.0-py3.8.egg/compliance_suite/test_runner.py", line 210, in validate_response
  File "/usr/local/lib/python3.8/site-packages/openapi_test_runner-0.1.0-py3.8.egg/compliance_suite/test_runner.py", line 232, in validate_filters
  File "<string>", line 1, in <module>
TypeError: 'NoneType' object is not subscriptable
Error response from daemon: Could not find the file /app/openapi-test-runner/results/report.json in container tes-test-container
```

**Comment by BMurri** [comment]
Version set to 1.0.0 works, except that things that changed in 1.1 fail in the 1.0.0 validation tests.

**Comment by uniqueg** [comment]
Thanks for reporting @BMurri. We are currently looking for a maintainer for the project and are unfortunately also in the middle of some considerable changes. So it might take a while to get this fixed.

We'd be happy to accept pull requests though, in case you are interested.

**Comment by vsmalladi** [comment]
Seems like the offending one is `create_task_ignore_error.yml` looking to see if I can get this to be fixed.
